
[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
# use ruff defaults: Flake8's F rules, along with a subset of the E rules, omitting any stylistic rules
# that overlap with the use of a formatter, like Black.
fixable = ["ALL"]
select = [
    "E",
    "F",
    "I", # isort
    "UP", # pyupgrade
    "S", # flake8-bandit
    "PGH", # pygrep-hooks
    "T100", # debug statements
    "W291", # trailing whitespace
    "W292" # no newline at end of file
]
ignore = [
    # https://docs.astral.sh/ruff/rules/#pydocstyle-d
    "D10", # missing docstrings (100 module, 101 class, 102 method ...)
    "D21", # whitespace and indentation,
    "S101" # use of assert
]
pydocstyle.convention = "pep257"

[tool.ruff.lint.isort]
lines-after-imports = 2
