[tool.ruff]
# Enable all linter rules by default.
select = ["ALL"]
# Exclude a few rules that might be too strict or not applicable to your project.
ignore = [
    "E501",  # Line too long (handled by formatter)
    "FBT001", # Boolean positional arg in function definition
    "ANN101", # Missing type annotation for self in method
    "ANN102", # Missing type annotation for cls in classmethod
]

# Configure the line length.
line-length = 88

# Enable auto-fixing for certain rules.
fix = true

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"] # Ignore unused imports in __init__.py files

[tool.ruff.format]
# Enable Ruff's built-in formatter.

